AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  liwanag-backend

  Sample SAM Template for liwanag-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Users"
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  patchUserById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/user_api/patchUserById
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            # RestApiId: "lghoog0yu1"
            Path: /users/{user_id}
            Method: patch

  getUserById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/user_api/getUserById
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            # RestApiId: "lghoog0yu1"
            Path: /users/{user_id}
            Method: get          

  postUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/user_api/postUser
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            # RestApiId: "lghoog0yu1"
            Path: /users
            Method: post
  
  getAllUsers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/user_api/getAllUsers
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            # RestApiId: "lghoog0yu1"
            Path: /users
            Method: get

